#pragma once

#define RESULT_CODE_BEGIN(...)
#define RESULT_CODE_END(...)
#define IGNORE_STRING_GENERATOR(...)

////////////////////////////////////////////////////////////////////////////////////
//msg header id
#define MSG_FLAG_IDFIELD_CONTENT			(uint16)0x3000
#define MSG_FLAG_IDFIELD_SERVER				(uint16)0x0800

#define IS_REQMSG(msgid)                    (((msgid) & MSG_FLAG_IDFIELD_REQMSG) == MSG_FLAG_IDFIELD_REQMSG)
#define IS_ACKMSG(msgid)                    (((msgid) & MSG_FLAG_IDFIELD_ACKMSG) == MSG_FLAG_IDFIELD_ACKMSG)
#define REQ_TO_ACK(msgid)					(((msgid) ^ MSG_FLAG_IDFIELD_REQMSG) | MSG_FLAG_IDFIELD_ACKMSG)

#define MAKE_ENGINEMSG(id, direction)       (uint16)(MSG_FLAG_IDFIELD_NET_ENGINE | (direction) | (id))

#define NETWORKMSG_CONNECTED                MAKE_ENGINEMSG(1, 0)
#define NETWORKMSG_DISCONNECTED             MAKE_ENGINEMSG(2, 0)

////////////////////////////////////////////////////////////////////////////////////
//packet
#define MSG_HEADER_SIZE_LENGTH	  (uint16)2
#define MSG_HEADER_SIZE_MSGID     (uint16)2
#define MSG_HEADER_SIZE           (uint16)(MSG_HEADER_SIZE_LENGTH + MSG_HEADER_SIZE_MSGID)

#define MAX_MSGBUF_SIZE           (uint16)4096
#define MSG_OFFSET_SIZE           (uint16)0
#define MSG_OFFSET_ID             (uint16)2
#define MAX_MESSIVE_BUF_SIZE      (uint16)65000
#define ERR_OUT_OF_MAX_SIZE       (uint16)0xFFFF

//////////////////////////////////////////////////////////////////////////////////////////
enum class UserLeaving : uint8 {
	Gracefull = 0,
	TimeOut,
	InternalError,
	AsyncTask,
	Protocol,
	Cheat,
	DuplicateLogin,

	Maintenance = 100,
	GM,
	Empty = 255,
};

//////////////////////////////////////////////////////////////////////////////////////////
#define MAKE_CONTENTMSG(dir, id)			(MSG_FLAG_IDFIELD_CONTENT | (dir) | id)
#define MAKE_SERVERMSG(dir, id)				(MSG_FLAG_IDFIELD_CONTENT | (uint16)0x0800 | (dir) | id)

#define ERROR_COMMON_MAX				COMMON_MAX + 0x01

//state update masks
#define STATE_MASK_LIFE					(uint8)(0x01)
#define STATE_MASK_BODY					(uint8)(0x02)
#define STATE_MASK_MOTION				(uint8)(0x04)
#define STATE_MASK_VITAL				(uint8)(0x08)
#define STATE_MASK_MOBILE				(uint8)(0x10)
#define STATE_MASK_ALL					(uint8)(0xff)

#define DUMMY_ACTION_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0001)
#define DUMMY_ACTION_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0001)
#define DUMMY_ACTION_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0001)
#define		DUMMY_ACTION_COMPLETED				(uint8)0x00
#define		DUMMY_ACTION_KEEP_RUNNING			(uint8)0x01
#define		DUMMY_ACTION_REPORT					(uint8)0x02
#define		DUMMY_ACTION_HAS_ERROR				(uint8)0x80

#define DUMMY_REDIRECT_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0004)
#define DUMMY_REDIRECT_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0004)

//////////////////////////////////////////////////////////////////////////////////////////
//global
#define CLIENT_ACCOUNT_INFO_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0002)

#define GLOBAL_TIMESYSTEM_SYNC_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0003)
#define GLOBAL_TIMESYSTEM_SYNC_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0003)

//////////////////////////////////////////////////////////////////////////////////////////
//world front-end
#define ENTER_WORLD_FRONT_END_LOBBY_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0010)
#define ENTER_WORLD_FRONT_END_LOBBY_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0010)
	#define ENTER_WORLD_FRONT_END_INTERNAL		(uint8)(ERROR_COMMON_MAX + 0x01)
	#define ENTER_WORLD_FRONT_END_NO_ENTRY		(uint8)(ERROR_COMMON_MAX + 0x02)

#define LIST_CHARACTER_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0011)
#define LIST_CHARACTER_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0011)

#define CREATE_CHARACTER_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0012)
#define CREATE_CHARACTER_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0012)
	#define SIMULATE_FAILE						(uint8)(ERROR_COMMON_MAX)
	#define INVALID_OBJECT_GUID					(uint8)(ERROR_COMMON_MAX + 0x01)
	#define USING_SLOTID						(uint8)(ERROR_COMMON_MAX + 0x02)
	#define QUERY_CREATE_CHARACTER				(uint8)(ERROR_COMMON_MAX + 0x03)
	#define QUERY_CHARACTER_ID					(uint8)(ERROR_COMMON_MAX + 0x04)
	#define QUERY_EQUIPMENT						(uint8)(ERROR_COMMON_MAX + 0x05)
	#define QUERY_INVENTORY						(uint8)(ERROR_COMMON_MAX + 0x06)
	#define QUERY_DEFAULT_ITEM					(uint8)(ERROR_COMMON_MAX + 0x07)
	#define QUERY_CURRENCY						(uint8)(ERROR_COMMON_MAX + 0x08)
	#define QUERY_CLASS							(uint8)(ERROR_COMMON_MAX + 0x09)
	#define QUERY_LOAD_CHARACTER				(uint8)(ERROR_COMMON_MAX + 0x0a)
	#define QUERY_CHANGE_NAME					(uint8)(ERROR_COMMON_MAX + 0x0b)
	#define QUERY_APPEARANCE					(uint8)(ERROR_COMMON_MAX + 0x0c)
	#define QUERY_CHATSTICKER					(uint8)(ERROR_COMMON_MAX + 0x0d)
	#define QUERY_SKILL							(uint8)(ERROR_COMMON_MAX + 0x0e)
	#define QUERY_SKILL_POINT					(uint8)(ERROR_COMMON_MAX + 0x0f)
	#define QUERY_SOCIALMOTION					(uint8)(ERROR_COMMON_MAX + 0x10)

#define CHARACTER_AMENITY_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0013)
#define CHARACTER_AMENITY_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0013)

#define CHANGE_CHARACTER_NICKNAME_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0015)
#define CHANGE_CHARACTER_NICKNAME_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0015)
	#define ERROR_NICKNAME_INVALID				(uint8)(0x01)
	#define ERROR_NICKNAME_FILTER				(uint8)(0x02)
#define CHANGE_CHARACTER_NICKNAME_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0015)

#define DISCONTINUE_SESSION					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0016)

#define ACCOUNT_WITHDRAW_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0017)
#define ACCOUNT_WITHDRAW_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0017)
	#define CHECK_WITHDRAW_CONDITION			(uint8)(0x01)

#define EXECUTE_CLIENT_RPC_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0018)

//////////////////////////////////////////////////////////////////////////////////////////
// ams auth 
#define IMAGE_UPLOAD_AUTH_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x001a)
#define IMAGE_UPLOAD_AUTH_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x001a)

#define TRANSLATE_AUTH_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x001b)

//////////////////////////////////////////////////////////////////////////////////////////
// world
#define CHANGE_WORLD_INSTANCE_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x001c)
#define CHANGE_WORLD_INSTANCE_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x001c)
	#define CHANGE_WORLD_INVALID_TARGET				(uint8)(0x01)
	#define CHANGE_WORLD_NOT_ALLOWD_INTERACTION		(uint8)(0x02)
	#define CHANGE_WORLD_TARGET_FULL				(uint8)(0x03)
	#define CHANGE_WORLD_ALREADY_ON_TARGET			(uint8)(0x04)

//////////////////////////////////////////////////////////////////////////////////////////
//world game
#define ENTER_GAME_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0020)
#define ENTER_GAME_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0020)
	#define QUERY_ACTIVE_CHARACTER				(uint8)(ERROR_COMMON_MAX + 0x01)

#define READY_TO_PLAY_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0021)
#define READY_TO_PLAY_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0021)

#define WORLD_OBJ_ADD_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0022)
	#define WORLD_OBJ_ADD_REASON_MIGRATED		(uint8)(0x00)
	#define WORLD_OBJ_ADD_REASON_ENTERED		(uint8)(0x01)
#define WORLD_OBJ_DEL_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0023)
	#define WORLD_OBJ_DEL_REASON_MIGRATED		(uint8)(0x00)
	#define WORLD_OBJ_DEL_REASON_LEFT			(uint8)(0x01)

#define WORLD_MIGRATION_STARTED_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0024)
	#define VALID_STAGE_DATA					(uint8)(0x01)
	#define INVALID_STAGE_DATA					(uint8)(0x02)

#define WORLD_OBJ_STAT_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0025)
	#define REQ_ORIGIN_STAT						(uint8)(0x00)
	#define REQ_BASE_STAT						(uint8)(0x01)
	#define REQ_SIMULATE_STAT					(uint8)(0x02)
	#define REQ_SIMULATE_EMPTYSLOT_STAT			(uint8)(0x03)
 
#define WORLD_OBJ_STAT_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0025)
	#define ACK_ORIGIN_STAT						(uint8)(0x00)
	#define ACK_BASE_STAT						(uint8)(0x01)
	#define ACK_SIMULATE_STAT					(uint8)(0x02)
#define WORLD_OBJ_STAT_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0025)

#define WORLD_OBJ_STATE_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0026)
#define WORLD_OBJ_VITAL_INFO_UPDATED_NFY	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0027)
#define WORLD_OBJ_MOBILE_INFO_UPDATED_NFY	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0028)
#define WORLD_OBJ_STANCE_UPDATED_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0029)
#define WORLD_OBJ_SHIELD_INFO_UPDATED_NFY	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x002a)

#define WORLD_TIME_DAY_TYPE_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x002a)
#define WORLD_TIME_DAY_TYPE_CHANGED_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x002b)

#define WORLD_OBJ_BEHAVIOR_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x002c)
		#define BEHAVIOR_NOTICE_TARGET			(uint8)(0x01)
		#define BEHAVIOR_LOOK_AT_TARGET			(uint8)(0x02)
		#define BEHAVIOR_RETREAT				(uint8)(0x03)
		#define BEHAVIOR_SYNC_MOTION			(uint8)(0x04)
		#define BEHAVIOR_SYNC_PHASE				(uint8)(0x05)

#define USE_PORTAL_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x002f)
	#define USE_PORTAL_ERROR_REFERENCE			(uint8)(0x01)
	#define USE_PORTAL_ERROR_CONDITION			(uint8)(0x02)
	#define USE_PORTAL_ERROR_MIGRATION			(uint8)(0x03)
#define USE_PORTAL_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x002f)

//////////////////////////////////////////////////////////////////////////////////////////
// user motion state
#define USER_SOCIAL_MOTION_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0030)
#define USER_SOCIAL_MOTION_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0030)
	#define USER_SM_ERROR_COMMON				(uint8)(0x00)
	#define USER_SM_ERROR_PC_STATE				(uint8)(0x01)
	#define USER_SM_ERROR_NOT_YET				(uint8)(0x02)

#define USER_SOCIAL_MOTION_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0031)

#define USER_BUSY_STATE_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0032)

#define USER_BLOCK_STATE_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0033)

#define USER_SOCIAL_MOTION_UPDATE_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0034)
	#define SOCIAL_MOTION_MOD_ADD				(uint8)(0x00)
	#define SOCIAL_MOTION_MOD_REMOVE			(uint8)(0x01)

//////////////////////////////////////////////////////////////////////////////////////////
//currency
#define CURRENCY_UPDATE_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0040)

#define CURRENCY_EXCHANGE_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0041)
#define CURRENCY_EXCHANGE_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0041)

//////////////////////////////////////////////////////////////////////////////////////////
//exp
#define FAVOR_UPDATE_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0042)

//////////////////////////////////////////////////////////////////////////////////////////
//reward period
#define REWARD_PERIOD_UPDATE_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x004a)
	#define	REWARD_PERIOD_ACTIVATE				(uint8)(0x00)
	#define	REWARD_PERIOD_DEACTIVATE			(uint8)(0x01)
	#define	REWARD_PERIOD_BROADCAST				(uint8)(0x02)

#define USE_PERIODIC_ITEM_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x004b)
#define USE_PERIODIC_ITEM_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x004b)

//////////////////////////////////////////////////////////////////////////////////////////
//move
IGNORE_STRING_GENERATOR()
#define MOVE_REQ							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0050)
#define MOVE_ACK							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0050)
	#define CAN_NOT_MOVE_STATE					(uint8)(ERROR_COMMON_MAX + 0x00)
	#define MSG_READ							(uint8)(ERROR_COMMON_MAX + 0x01)
	#define ACK_MOVE_NEED_CORRECTION			(uint8)(ERROR_COMMON_MAX + 0x02)
	#define ACK_MOVE_NEED_REQUEST				(uint8)(ERROR_COMMON_MAX + 0x03)
IGNORE_STRING_GENERATOR()
#define MOVE_NFY							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0050)

IGNORE_STRING_GENERATOR()
#define MOVE_TO_REQ							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0051)
#define MOVE_TO_ACK							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0051)
#define MOVE_TO_NFY							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0051)
#define JUMP_REQ							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0052)
#define JUMP_ACK							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0052)
	#define JUMP_ERROR_ALREADY_FALLING			(uint8)0x01
	#define JUMP_ERROR_NEED_CORRECTION			(uint8)0x02
	#define JUMP_ERROR_INVALID_MOTION			(uint8)0x03

#define MOVE_LOCATION_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0053)
#define MOVE_WITH_CONSTANT_VELOCITY_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0054)

#define DASH_REQ							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0055)
#define DASH_ACK							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0055)
#define DASH_NFY							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0055)

#define RESET_LOCATION_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0056)
#define RESET_LOCATION_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0056)

IGNORE_STRING_GENERATOR()
#define MOVE_SNAPSHOT_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0057)
#define MOVE_SNAPSHOT_INIT_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0058)
#define MOVE_SNAPSHOT_INIT_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0058)
#define MOVE_SNAPSHOT_INIT_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0058)
IGNORE_STRING_GENERATOR()
#define MOVE_SNAPSHOT_PATCH_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0059)

RESULT_CODE_BEGIN(RESULT_MOVE_SNAPSHOT)
#	define RESULT_MOVE_SNAPSHOT_SUCCEEDED		(uint8)0x00
#	define RESULT_MOVE_SNAPSHOT_ALREADY_QUEUED	(uint8)0x01
#	define RESULT_MOVE_SNAPSHOT_FAILED			(uint8)0x80
RESULT_CODE_END()

#	define SUCCEEDED_RESULT_MOVE_SNAPSHOT(x)	((x) <  (uint8)0x80)
#	define FAILED_RESULT_MOVE_SNAPSHOT(x)		((x) >= (uint8)0x80)

#define MOVE_HISTORY_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x005b)
#define NAVMESH_FINDING_SURFACE_FAILED_NFY	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x005c)
#define NAVMESH_RESOLVE_NEXT_LOCATION_NFY	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x005d)

#define IMPULSE_NFY							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x005e)
#define FALLING_NFY							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x005f)

//////////////////////////////////////////////////////////////////////////////////////////
//chat
#define CHAT_REQ						    MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0060)
#define CHAT_ACK					        MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0060)
	#define CHAT_ERROR_COMMAND					(uint8)(ERROR_COMMON_MAX + 0x01) 
	#define CHAT_ERROR_WRONG_CHANNEL			(uint8)(ERROR_COMMON_MAX + 0x02) 
	#define CHAT_ERROR_DEFFERNT_CHANNEL			(uint8)(ERROR_COMMON_MAX + 0x03)
	#define CHAT_ERROR_TABLE_EMPTY				(uint8)(ERROR_COMMON_MAX + 0x04) 
	#define CHAT_ERROR_LONG_MSG					(uint8)(ERROR_COMMON_MAX + 0x05)
	#define CHAT_ERROR_USER						(uint8)(ERROR_COMMON_MAX + 0x06) 
	#define CHAT_ERROR_BAN						(uint8)(ERROR_COMMON_MAX + 0x07) 

#define CHAT_NFY					        MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0060)

#define CHAT_CHANNEL_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0061)
	#define CHAT_CHANNEL_ACTIVE					(uint8)(0x01)
	#define CHAT_CHANNEL_LEAVE					(uint8)(0x02)
	#define CHAT_CHANNEL_UPDATE					(uint8)(0x03)

#define CHAT_HISTORY_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0062)
#define CHAT_HISTORY_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0062)

#define CHAT_STICKER_GROUP_UPDATE_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0063)
	#define CHAT_STICKER_MOD_LOADED				(uint8)(0x00)
	#define CHAT_STICKER_MOD_ADD				(uint8)(0x01)
	#define CHAT_STICKER_MOD_REMOVE				(uint8)(0x02)

#define CHAT_TOAST_NFY					    MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0065)

//////////////////////////////////////////////////////////////////////////////////////////
//permission
#define PERMISSION_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0070)
	#define PERMISSION_CMD_INIT					(uint8)0X00
	#define PERMISSION_CMD_ADD					(uint8)0X01
	#define PERMISSION_CMD_DEL					(uint8)0X02

#define SERVER_SCHEDULE_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0071)

//////////////////////////////////////////////////////////////////////////////////////////
//palette
#define PALETTE_LIST_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0075)
#define PALETTE_LIST_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0075)

//////////////////////////////////////////////////////////////////////////////////////////
//life object
#define LIFEOBJ_UPDATED_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0080)

#define LIFEOBJ_INTERACTION_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0082)
#define LIFEOBJ_INTERACTION_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0082)
	#define LIFEOBJ_ERROR_INVALID_TARGET				(uint8)(0x01)
	#define LIFEOBJ_ERROR_INVALID_INSTANCE				(uint8)(0x02)
	#define LIFEOBJ_ERROR_TOO_FAR						(uint8)(0x03)
	#define LIFEOBJ_ERROR_NOT_CLASS_LICENSE				(uint8)(0x04)
	#define LIFEOBJ_ERROR_NOT_ENOUGH_CURRENCY_AMOUNT	(uint8)(0x05)
	#define LIFEOBJ_ERROR_SHARED_MAX					(uint8)(0x06)
	#define LIFEOBJ_ERROR_ALREADY_ATTACHED				(uint8)(0x07)
	#define LIFEOBJ_ERROR_PC_BLOCK_STATE				(uint8)(0x08)
	#define LIFEOBJ_ERROR_PERMISSION_DENIED				(uint8)(0x09)

#define LIFEOBJ_INTERACTION_START_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0083)
#define LIFEOBJ_INTERACTION_END_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0084)

#define LIFEOBJ_CHANGE_AMOUNT_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0085)

#define LIFEOBJ_MINIGAME_END_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0086)
#define LIFEOBJ_MINIGAME_END_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0086)

#define SCHEDULE_ACTOR_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0087)

//////////////////////////////////////////////////////////////////////////////////////////
//skill
#define SKILL_USE_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0090)
#define SKILL_USE_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0090)
	#define SKILL_USE_ERROR_BLOCK_STATE			(uint8)(ERROR_COMMON_MAX + 0x01)
	#define SKILL_USE_ERROR_ENGAGE				(uint8)(ERROR_COMMON_MAX + 0x02)
	#define SKILL_USE_ERROR_FIRE				(uint8)(ERROR_COMMON_MAX + 0x03)
	#define SKILL_USE_ERROR_COOLTIME			(uint8)(ERROR_COMMON_MAX + 0x04)
	#define SKILL_USE_ERROR_INSTANCE			(uint8)(ERROR_COMMON_MAX + 0x05)
	#define SKILL_USE_ERROR_TARGET_COUNT		(uint8)(ERROR_COMMON_MAX + 0x06)

#define SKILL_STATE_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0091)
#define SKILL_EFFECT_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0092)
#define SKILL_COOLTIME_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0093)
#define SKILL_INDICATOR_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0094)

#define SKILL_CHARGE_START_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0095)
#define SKILL_CHARGE_START_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0095)
	#define CHARGE_SKILL_NOT_FOUND_REFERENCE	(uint8)(ERROR_COMMON_MAX + 0x01)
#define SKILL_CHARGE_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0095)
	#define CHARGE_SKILL_STARTED				(uint8)0x01
	#define CHARGE_SKILL_FAILED					(uint8)0x02
#define SKILL_CHARGE_END_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0096)
	#define FIRE_SKILL_NOT_ENOUGH_CHARGE		(uint8)0x01
	#define FIRE_SKILL_ERROR_ENGAGED			(uint8)0x02
	#define FIRE_SKILL_ERROR_ALREADY_FIRED		(uint8)0x03
#define SKILL_CHARGE_END_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0096)

#define SKILL_CANCEL_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0097)

#define CHANGE_TO_PLAYABLE_STATE_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0098)
#define CHANGE_TO_PLAYABLE_STATE_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0098)	
	#define CHANGE_TO_PLAYABLE_STATE				(uint8)0x02
	#define CHANGE_TO_PLAYABLE_STATE_COOLTIME		(uint8)0x03
	#define CHANGE_TO_PLAYABLE_STATE_NOT_SUPPORTED	(uint8)0x04

#define SKILL_DBG_DRAW_RANGE_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x009f)

//////////////////////////////////////////////////////////////////////////////////////////
// title
#define TITLE_LIST_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00a0)
#define TITLE_LIST_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00a0)

#define TITLE_EQUIP_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00a1)
#define TITLE_EQUIP_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00a1)

#define TITLE_ADD_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x00a2)
#define TITLE_OWNERSHIP_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x00a3)

//////////////////////////////////////////////////////////////////////////////////////////
// match make
#define MATCH_MAKE_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00b0)
#define MATCH_MAKE_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00b0)
	#define MATCH_MAKE_FAIL_COMMON						(uint8)0x01
	#define MATCH_MAKE_FAIL_OVER_BUILD_TIME				(uint8)0x02
	#define MATCH_INVALID_TEAM_INFO						(uint8)0x03
	#define MATCH_MEMBER_NOT_EXISTS						(uint8)0x04
	#define MATCH_MAKE_FAIL_FULL_PLAYERS				(uint8)0x05
	#define MATCH_MAKE_FAIL_FULL_SPECTATORS				(uint8)0x06
	#define MATCH_MAKE_FAIL_NOT_SUPPORTED_QUICK_MATCH	(uint8)0x07
	#define MATCH_MAKE_FAIL_STAGE_CLOSED				(uint8)0x08
	#define MATCH_INVALID_WORLD							(uint8)0x09
#define MATCH_MAKE_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x00b0)

//////////////////////////////////////////////////////////////////////////////////////////
// photogrpr gallery(topic)
#define GALLERY_UPLOAD_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00c0)
#define GALLERY_UPLOAD_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00c0)

#define GALLERY_LIST_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00c1)
	#define GALLERY_LIST_CMD_TOP				(uint8)(0x00)
	#define GALLERY_LIST_CMD_TAG_SCORE			(uint8)(0x01)
	#define GALLERY_LIST_CMD_TAG_NEWEST			(uint8)(0x02)
#define GALLERY_LIST_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00c1)

#define GALLERY_FEEDBACK_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00c2)
	#define GALLERY_FEEDBACK_CMD_LIKE			(uint8)(0x01)
	#define GALLERY_FEEDBACK_CMD_REPORT			(uint8)(0x02)
#define GALLERY_FEEDBACK_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00c2)
#define GALLERY_FEEDBACK_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x00c2)

#define GALLERY_USER_BLIND_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00c3)
#define GALLERY_USER_BLIND_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00c3)

#define GALLERY_GUESTBOOK_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00c4)
	#define GALLERY_GSTB_CMD_LIST				(uint8)(0x01)
	#define GALLERY_GSTB_CMD_ADD				(uint8)(0x02)
	#define GALLERY_GSTB_CMD_DELETE				(uint8)(0x04)
#define GALLERY_GUESTBOOK_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00c4)
	#define GALLERY_GBST_ERROR_STRING			(uint8)(0x01)

#define GALLERY_CMD_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00c5)
	#define GALLERY_CMD_SEARCH					(uint8)(0x01)
	#define GALLERY_CMD_DETAIL					(uint8)(0x02)
	#define GALLERY_CMD_CLIENT						(uint8)(0x03)
#define GALLERY_CMD_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00c5)

#define GALLERY_OWNER_CMD_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x00c6)
	#define GALLERY_OWNER_CMD_DELETE			(uint8)(0x01)
	#define GALLERY_OWNER_CMD_MSG				(uint8)(0x02)
	#define GALLERY_OWNER_CMD_GUESTBOOK			(uint8)(0x03)
#define GALLERY_OWNER_CMD_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x00c6)

//////////////////////////////////////////////////////////////////////////////////////////
//item 
#define ITEM_UPDATED_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x01f0)

#define UPGRADE_ITEM_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x01f1)
#define UPGRADE_ITEM_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x01f1)
	#define UPGRADE_ITEM_SUCCESS				(uint8)(ERROR_COMMON_MAX + 0x00)
	#define UPGRADE_ITEM_FAIL_COMMON			(uint8)(ERROR_COMMON_MAX + 0x01)
	#define UPGRADE_ITEM_FAIL_MATERIAL_ITEM		(uint8)(ERROR_COMMON_MAX + 0x02)
	#define UPGRADE_ITEM_FAIL_CURRENCY			(uint8)(ERROR_COMMON_MAX + 0x03)

#define UPGRADE_TRANSCENDENCE_ITEM_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x01f3)
#define UPGRADE_TRANSCENDENCE_ITEM_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x01f3)

#define UPGRADE_EMBLEM_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x01f4)
#define UPGRADE_EMBLEM_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x01f4)

#define UPGRADE_EMBLEM_TRANSCENDENCE_REQ	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x01f5)
#define UPGRADE_EMBLEM_TRANSCENDENCE_ACK	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x01f5)

#define ASSEMBLE_EMBLEM_PIECE_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x01f6)
#define ASSEMBLE_EMBLEM_PIECE_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x01f6)

#define UPDATE_ITEM_ATTRIBUTE_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x01f7)
#define UPDATE_ITEM_ATTRIBUTE_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x01f7)
#	define UPDATE_ITEM_ATTRIBUTE_LOCKED			(uint8)(1)

#define USE_ITEM_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0103)
#define USE_ITEM_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0103)
	#define USE_EFFECT_FAIL_EXCEED_CHARGE		(uint8)(ERROR_COMMON_MAX + 0x02)
	#define USE_EFFECT_FAIL_INVALID_CLASS		(uint8)(ERROR_COMMON_MAX + 0x03)
	#define USE_EFFECT_FAIL_DUPLICATE			(uint8)(ERROR_COMMON_MAX + 0x04)

#define CRAFT_EQUIP_ITEM_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0104)
#define CRAFT_EQUIP_ITEM_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0104)

#define SHOP_ITEM_LIST_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0105)
#define SHOP_ITEM_LIST_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0105)
#define SHOP_ITEM_LIST_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0105)

#define SHOP_ITEM_BUY_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0106)
#define SHOP_ITEM_BUY_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0106)
	#define SHOP_ITEM_BUY_FAIL_COMMON			(uint8)(ERROR_COMMON_MAX + 0x01)
	#define SHOP_ITEM_BUY_FAIL_SHORT_CURRENCY	NOT_ENOUGH_COUNT
	#define SHOP_ITEM_BUY_FAIL_SCHEDULE			(uint8)(ERROR_COMMON_MAX + 0x02)
	#define SHOP_ITEM_BUY_FAIL_BUY_COUNT_MAX	(uint8)(ERROR_COMMON_MAX + 0x03)	
	#define SHOP_ITEM_BUY_FAIL_CONDITION		(uint8)(ERROR_COMMON_MAX + 0x05)
	#define SHOP_ITEM_BUY_FAIL_UNLOCK			(uint8)(ERROR_COMMON_MAX + 0x06)
	#define SHOP_ITEM_BUY_FAIL_DEACTIVATE		(uint8)(ERROR_COMMON_MAX + 0x07)

#define EMBLEM_EQUIP_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0107)
#define EMBLEM_EQUIP_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0107)
#define EMBLEM_EQUIP_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0107)

#define REWARD_NFY							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0108)
	#define REWARD_SRC_COMMON					(uint8)0x00
	#define REWARD_SRC_REWARD					(uint8)0x01

#define SHOP_PAYMENT_RETRY_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0109)
	#define PAYMENT_CONSUMABLE					(uint8)0x00
	#define PAYMENT_SUBSCRIPTION				(uint8)0x01
#define SHOP_PAYMENT_RETRY_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0109)

//#define EQUIP_COLLECTION_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x010a)

#define SHOP_PAYMENT_PRECHECK_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x010b)
#define SHOP_PAYMENT_PRECHECK_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x010b)

#define EXTRACT_SKIN_ITEM_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x010c)
	#define SKIN_EXTRACT						(uint8)0x00
	#define SKIN_APPLY							(uint8)0x01
	#define SKIN_RESET							(uint8)0x02
	#define SKIN_REPLACE						(uint8)0x03
#define EXTRACT_SKIN_ITEM_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x010c)
	#define EXTRACT_SKIN_ITEM_FAIL_COMMON		(uint8)(ERROR_COMMON_MAX + 0x01)

#define EMBLEM_UNEQUIP_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x010d)
#define EMBLEM_UNEQUIP_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x010d)

//////////////////////////////////////////////////////////////////////////////////////////
//equip collection
#define EQUIP_COLLECTION_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x010a)
#define EQUIP_COLLECTION_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x010a)

//#define SHOP_PAYMENT_PRECHECK_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x010b)

//////////////////////////////////////////////////////////////////////////////////////////
//class
#define CLASS_UPDATE_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0110)
	#define CLASS_MOD_LOADED						(uint8)(0x01)
	#define CLASS_MOD_NEW							(uint8)(0x02)
	#define CLASS_MOD_UPDATED						(uint8)(0x04)
	#define CLASS_MOD_DELETE						(uint8)(0x08)

#define CLASS_CHANGE_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0111)
#define CLASS_CHANGE_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0111)

#define CLASS_SKILL_UPDATE_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0112)

#define CLASS_LICENSE_MASTERY_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0113)

#define CLASS_LICENSE_GAIN_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0114)

//////////////////////////////////////////////////////////////////////////////////////////
//fashion contents
#define FASHION_SHOW_INFO_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0120)
#define FASHION_SHOW_INFO_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0120)

#define FASHION_CONTENTS_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0120)

#define FASHION_SHOW_JOIN_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0121)
	#define FS_CMD_MODEL						(uint8)(0x01)
	#define FS_CMD_OBSERVER						(uint8)(0x02)
#define FASHION_SHOW_JOIN_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0121)

#define FASHION_SHOW_CMD_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0122)
	#define FS_CMD_POSE							(uint8)(0x02)
	#define FS_CMD_VOTE							(uint8)(0x03)
	#define FS_CMD_DONATION						(uint8)(0x04)
#define FASHION_SHOW_CMD_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0122)
#define FASHION_SHOW_CMD_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0122)
	#define FS_CMD_NFY_DONATION					(uint8)(0x01)
	#define FS_CMD_NFY_END						(uint8)(0x02)

#define FASHION_AUDITION_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0124)
	#define FA_CMD_INFO							(uint8)(0x00)
	#define FA_CMD_JOIN							(uint8)(0x01)
	#define FA_CMD_BATTLE_NPC					(uint8)(0x02)
	#define FA_CMD_MATCH_REFRESH				(uint8)(0x03)
#define FASHION_AUDITION_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0124)

#define FASHION_AUDITION_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0124)
	#define FA_NFY_ALL							(uint8)(0x01)
	#define FA_NFY_TARGET_PLAYER				(uint8)(0x02)

#define FASHION_AUDITION_SEASON_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0125)
	#define FA_STAGE_UPDATE						(uint8)(0x01)
	#define FA_SEASON_UPDATE					(uint8)(0x02)

#define FASHION_AUDITION_BATTLE_START_REQ	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0126)
	#define FAB_ERROR_TARGET_STATE				(uint8)(0x01)
#define FASHION_AUDITION_BATTLE_START_ACK	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0126)
#define FASHION_AUDITION_BATTLE_START_NFY	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0126)
	#define FA_BATTLE_PC						(uint8)(0x02)
	#define FA_BATTLE_NPC						(uint8)(0x03)

#define FASHION_AUDITION_BATTLE_END_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0127)
#define FASHION_AUDITION_BATTLE_END_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0127)

#define FASHION_AUDITION_RANK_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0128)
#define FASHION_AUDITION_RANK_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0128)

#define FASHION_AUDITION_RANKER_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0129)
#define FASHION_AUDITION_RANKER_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0129)

#define FASHION_SHOW_RANKING_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x012a)
#define FASHION_SHOW_RANKING_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x012a)

//////////////////////////////////////////////////////////////////////////////////////////
//crew
#define CREW_ERROR_DEACTIVE						(uint8)0x99
#define CREW_CMD_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0130)
	#define CREW_CMD_LIST						(uint8)0x01
	#define CREW_CMD_CREATE						(uint8)0x02
	#define CREW_CMD_SIGN_UP					(uint8)0x03
	#define CREW_CMD_SIGN_OUT					(uint8)0x04
	#define CREW_CMD_SEARCH						(uint8)0x05
	#define CREW_CMD_INVITE_CANCEL				(uint8)0x07
	#define CREW_CMD_APPLY_CANCEL				(uint8)0x08
#define CREW_CMD_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0130)
	#define CREW_CREATE_ERROR_DUPLICATE			(uint8)0x01
	#define CREW_CREATE_ERROR_NAME				(uint8)0x02
	#define CREW_SIGNUP_ERROR_FULL				(uint8)0x03
	#define CREW_SIGNUP_ERROR_STATE_UPDATE		(uint8)0x04
	#define CREW_SIGNUP_ERROR_CANCEL			(uint8)0x05

#define CREW_MASTER_CONTENTS_CMD_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0131)
	#define CREW_M_CONTENTS_CMD_NOTICE			(uint8)0x01
	#define CREW_M_CONTENTS_CMD_DESC			(uint8)0x02
	#define CREW_M_CONTENTS_CMD_APPROVAL		(uint8)0x03
	#define CREW_M_CONTENTS_CMD_IMAGE			(uint8)0x04
#define CREW_MASTER_CONTENTS_CMD_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0131)

#define CREW_MASTER_MANAGE_CMD_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0132)
	#define CREW_M_MANAGE_CMD_EXPEL				(uint8)0x01
	#define CREW_M_MANAGE_CMD_APPLY				(uint8)0x02
	#define CREW_M_MANAGE_CMD_INVITE			(uint8)0x03
#define CREW_MASTER_MANAGE_CMD_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0132)
	#define CREW_M_MANAGE_ERROR_INVITE_CNT		(uint8)0x01
	#define CREW_M_MANAGE_ERROR_INVITE_NAME		(uint8)0x02
	#define CREW_M_MANAGE_ERROR_INVITE_PERRMIT	(uint8)0x03
	#define CREW_M_MANAGE_ERROR_CONFIRM_SIGNUP	(uint8)0x04

#define CREW_MASTER_MANAGE_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0132)
	#define CREW_M_MANAGE_MANAGE				(uint8)0x01

#define CREW_MEMBER_CMD_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0133)
	#define CREW_MEMBER_CMD_INFO				(uint8)0x01
	#define CREW_MEMBER_WARP					(uint8)0x02
#define CREW_MEMBER_CMD_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0133)

#define CREW_MEMBER_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0134)
	#define CREW_MEMBER_LIST					(uint8)0x00
	#define CREW_MEMBER_SIGN_UP					(uint8)0x01
	#define CREW_MEMBER_SIGN_OUT				(uint8)0x02
	#define CREW_MEMBER_EXPEL					(uint8)0x03

#define CREW_INFO_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0135)

#define CREW_INTERACTION_LIST_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0136)
#define CREW_INTERACTION_LIST_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0136)
#define CREW_INTERACTION_LIST_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0136)

//////////////////////////////////////////////////////////////////////////////////////////
//quest
#define QUEST_CLIENT_TASK_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0140)
#define QUEST_ADD_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0141)

#define QUEST_ACCEPT_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0142)
#define QUEST_ACCEPT_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0142)
	#define	QUEST_ACCEPT_SUCCESS				(uint8)0x01
	#define	QUEST_ACCEPT_FAIL_COMMON			(uint8)0x02
	#define	QUEST_ACCEPT_FAIL_TOO_FAR			(uint8)0x03
	#define	QUEST_ACCEPT_FAIL_CONDITION			(uint8)0x04
	#define	QUEST_ACCEPT_FAIL_PROGRESS			(uint8)0x05
	#define QUEST_ACCEPT_FAIL_TIMEOUT			(uint8)0x06

#define QUEST_REWARD_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0143)
#define QUEST_REWARD_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0143)

#define QUEST_COMPLETE_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0144)
	#define QUEST_COMPLETE						(uint8)0x01
	#define SEQUENCE_COMPLETE					(uint8)0x02
	#define NO_COMPLETE							(uint8)0x03

#define QUEST_GIVEUP_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0145)
#define QUEST_GIVEUP_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0145)
	#define QUEST_GIVEUP_SUCCESS				(uint8)0x01
	#define QUEST_GIVEUP_FAIL_OVER_COUNT		(uint8)0x02

#define QUEST_RUNTIME_ADD_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0146)
	#define RTQUEST_ADD_CMD_NORMAL				(uint8)0x01
	#define RTQUEST_ADD_CMD_CLASS_LICENSE		(uint8)0x02
#define QUEST_RUNTIME_ADD_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0146)
	#define QUEST_RUNTIME_ADD_SUCCESS			(uint8)0x01
	// ...QUEST_ACCEPT_FAIL...
	#define QUEST_RUNTIME_ADD_FAIL_DEACTIVATE	(uint8)0x07
	#define QUEST_RUNTIME_ADD_FAIL_RUNOUT_COUNT	(uint8)0x08
	#define QUEST_RUNTIME_ADD_FAIL_INVALID_ITEM	(uint8)0x09
	#define QUEST_RUNTIME_ADD_FAIL_FROG			(uint8)0x0A

#define QUEST_LIST_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0147)

#define QUEST_CLIENT_TASK_COMPLETE_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0148)
#define QUEST_CLIENT_TASK_COMPLETE_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0148)
	#define QUEST_CLIENT_TASK_FAIL_CONDITION	(uint8)0x01
	#define QUEST_CLIENT_TASK_FAIL_COST			(uint8)0x02
	#define QUEST_CLIENT_TASK_FAIL_EXPIRED		(uint8)0x03
	#define QUEST_CLIENT_TASK_FAIL_RUNOUT		(uint8)0x04

#define QUEST_RUNTIME_LIST_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0149)
#define QUEST_RUNTIME_LIST_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0149)
	#define RTQUEST_LIST_CMD_QUEST				(uint8)0x01
	#define RTQUEST_LIST_CMD_RANK				(uint8)0x02
	#define RTQUEST_LIST_CMD_SCHEDULE			(uint8)0x03
	#define RTQUEST_LIST_CMD_CHALLENGE			(uint8)0x05
	#define RTQUEST_LIST_CMD_ARBEIT_RESERVE		(uint8)0x06

#define QUEST_RUNTIME_LIST_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x014b)

#define QUEST_REWARD_SELECTABLE_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x014c)
#define QUEST_REWARD_SELECTABLE_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x014c)

#define QUEST_TEAM_INFO_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x014d)
	#define QUEST_TEAM_UPDATED					(uint8)0x01
	#define QUEST_TEAM_FINISHED					(uint8)0x02

#define QUEST_MANUAL_RETRY_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x014e)
#define QUEST_MANUAL_RETRY_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x014e)

#define LOAD_QUEST_SEQUENCE_REWARD_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x014f)

//////////////////////////////////////////////////////////////////////////////////////////
#define STAGE_START_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0151)
#define STAGE_START_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0151)
	#define STAGE_START_ERROR_INTERNAL			(uint8)(ERROR_COMMON_MAX + 0x00)
	#define STAGE_START_ERROR_CURRENCY			(uint8)(ERROR_COMMON_MAX + 0x01)
	#define STAGE_START_ERROR_STATE				(uint8)(ERROR_COMMON_MAX + 0x02)
	#define STAGE_START_ERROR_PARAM				(uint8)(ERROR_COMMON_MAX + 0x03)
	#define STAGE_START_ERROR_SCHEDULE			(uint8)(ERROR_COMMON_MAX + 0x04)
	#define STAGE_START_ERROR_ENTER_COUNT		(uint8)(ERROR_COMMON_MAX + 0x05)

#define STAGE_STATE_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0152)
	#define STAGE_ROUND_START					(uint8)0x01
	#define STAGE_ROUND_WAIT					(uint8)0x02
	#define STAGE_ROUND_EVENT_UPDATED			(uint8)0x03
	#define STAGE_ROUND_CLEAR					(uint8)0x04
	#define STAGE_SUCCEED						(uint8)0x05

#define STAGE_LEAVE_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0153)
#define STAGE_LEAVE_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0153)

#define STAGE_REVIVAL_WAIT_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0154)

#define STAGE_PLAYER_CONTENTS_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0155)
	#define STAGE_PLAYER_CONTRIBUTION			(uint8)0x01

#define STAGE_TEAM_INFO_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0156)

#define LEVELDESIGN_START_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0157)
#define LEVELDESIGN_END_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0158)

#define STAGE_EVENT_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0159)
	#define STAGE_MOD_CHANGE					(uint8)0x01

#define STAGE_DATA_UPDATE_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x015a)
#define NPC_SKIN_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x015b)

//////////////////////////////////////////////////////////////////////////////////////////
//equip & costume
#define EQUIP_ITEM_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0160)
#define EQUIP_ITEM_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0160)
	#define EQUIP_ITEM_FAIL_COOLTIME			(uint8)(ERROR_COMMON_MAX + 0x01)
	#define UNKNOWN_EQUIP_ITEM					(uint8)(ERROR_COMMON_MAX + 0x02)
	#define WRONG_SLOTID						(uint8)(ERROR_COMMON_MAX + 0x03)
	#define ALREADY_EQUIPED_ITEM				(uint8)(ERROR_COMMON_MAX + 0x04)

#define EQUIP_ITEM_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0161)

#define CARVE_ITEM_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0162)
	#define CARVE_CMD_STAGE						(uint8)0x00
	#define CARVE_CMD_COMMIT					(uint8)0x01
#define CARVE_ITEM_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0162)

//costume
#define COSTUME_EQUIP_ITEM_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0163)
#define COSTUME_EQUIP_ITEM_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0163)

#define COSTUME_CUSTOMIZE_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0164)
#define COSTUME_CUSTOMIZE_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0164)
	#define CUSTOMIZE_ERROR_COMMON					(uint8)0x01
	#define CUSTOMIZE_ERROR_DYEING_ITEM				(uint8)0x02

#define COSTUME_PRESET_SET_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0165)
#define COSTUME_PRESET_SET_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0165)

#define COSTUME_PRESET_QUICK_CHANGE_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0166)
#define COSTUME_PRESET_QUICK_CHANGE_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0166)
	#define PRESET_CHANGE_COOLTIME				(uint8)(ERROR_COMMON_MAX + 0x01)

#define COSTUME_EQUIP_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0167)

#define COSTUME_SNAP_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0168)
#define COSTUME_SNAP_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0168)
#define COSTUME_SNAP_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0168)

#define COSTUME_LIST_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0169)
#define COSTUME_LIST_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0169)

#define MAGICSHOP_CONFIRM_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x016a)
	#define MAGICSHOP_FAILED_REFERENCE			(uint8)0x01;
	#define MAGICSHOP_FAILED_PERMITTED			(uint8)0x02;
#define MAGICSHOP_CONFIRM_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x016a)
#define MAGICSHOP_CONFIRM_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x016a)

#define PIGMENT_CRAFT_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x016b)
#define PIGMENT_CRAFT_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x016b)

#define COSTUME_PRESET_PURCHASE_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x016c)
#define COSTUME_PRESET_PURCHASE_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x016c)

//////////////////////////////////////////////////////////////////////////////////////////
// quest challenge
#define QUEST_CHALLENGE_EXCHANGE_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0170)
#define QUEST_CHALLENGE_EXCHANGE_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0170)

#define QUEST_CHALLENGE_RANK_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0171)
#define QUEST_CHALLENGE_RANK_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0171)
#define QUEST_CHALLENGE_RANK_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0171)

#define QUEST_CHALLENGE_SUBMIT_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0172)
	#define QC_SUBMIT_HOST						(uint8)0x01
	#define QC_SUBMIT_IMAGE						(uint8)0x02
#define QUEST_CHALLENGE_SUBMIT_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0172)
#define QUEST_CHALLENGE_SUBMIT_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0172)

#define QUEST_CHALLENGE_MYINFO_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0173)
#define QUEST_CHALLENGE_MYINFO_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0173)

#define QUEST_CHALLENGE_CEREMONY_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0174)
#define QUEST_CHALLENGE_CEREMONY_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0174)
	#define QC_CEREMONY_EXPIRED					(uint8)(0x01)

#define QUEST_CHALLENGE_RANKER_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0175)
#define QUEST_CHALLENGE_RANKER_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0175)

#define QUEST_CHALLENGE_SPOT_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0176)

//////////////////////////////////////////////////////////////////////////////////////////
// user request
#define USER_GROUP_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0180)
#define USER_GROUP_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0180)

#define USER_PROFILE_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0181)
#define USER_PROFILE_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0181)
#define USER_PROFILE_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0181)

#define USER_INTERACTION_DATA_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0182)

#define USER_INTERACTION_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0183)
	#define USER_REQUEST_FAIL_COMMON			(uint8)(0x01)
	#define USER_REQUEST_FAIL_TUTORIAL			(uint8)(0x02)
	#define USER_REQUEST_FAIL_NO_TARGET			(uint8)(0x03)
	#define USER_REQUEST_FAIL_BUSY				(uint8)(0x04)
	#define USER_REQUEST_FAIL_COOLTIME			(uint8)(0x05)
	#define USER_REQUEST_FAIL_LIMIT_COUNT		(uint8)(0x06)
#define USER_INTERACTION_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0183)
#define USER_INTERACTION_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0183)

#define USER_FRIEND_ADD_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0184)
	#define FRIEND_ADD_FAIL_LIMIT_COUNT			(uint8)(0x01)
	#define FRIEND_ADD_FAIL_INVALID_STATE		(uint8)(0x02)
	#define FRIEND_ADD_FAIL_REQUEST_LIMIT		(uint8)(0x03)
	#define FRIEND_ADD_FAIL_MY_LIMIT_COUNT		(uint8)(0x04)
	#define FRIEND_ADD_FAIL_EXPIRED				(uint8)(0x05)
#define USER_FRIEND_ADD_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0184)

#define USER_FRIEND_LIST_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0185)
	#define FRIEND_LIST_SCOPE_START				(uint8)(0x01)
	#define FRIEND_LIST_SCOPE_SEND				(uint8)(0x02)
	#define FRIEND_LIST_SCOPE_APPLY				(uint8)(0x03)

#define USER_PROFILE_EDIT_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0188)
	#define PROFILE_EDIT_CARD_IMAGE				(uint8)(0x01)
	#define PROFILE_EDIT_THUMBNAIL				(uint8)(0x02)
	#define PROFILE_EDIT_COMMENT				(uint8)(0x03)
	#define PROFILE_EDIT_INTERESTS				(uint8)(0x04)
#define USER_PROFILE_EDIT_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0188)

#define USER_FRIEND_CONTENTS_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0189)
#define USER_FRIEND_CONTENTS_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0189)
	#define FRIEND_CONTENTS_FAIL_REGION					(uint8)(0x01)
	#define FRIEND_CONTENTS_FAIL_MIGRATION				(uint8)(0x02)
	#define FRIEND_CONTENTS_FAIL_MIGRATION_STATE		(uint8)(0x03)
	#define FRIEND_CONTENTS_FAIL_MIGRATION_TAGET_FULL	(uint8)(0x04)

#define USER_GUESTBOOK_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x018a)
	#define USER_GSTB_CMD_LIST					(uint8)(0x01)
	#define USER_GSTB_CMD_ADD					(uint8)(0x02)
	#define USER_GSTB_CMD_DELETE				(uint8)(0x04)
#define USER_GUESTBOOK_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x018a)
	#define GUEST_GBST_ERROR_STRING				(uint8)(0x01)

#define USER_GUESTBOOK_READ_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x018b)
#define USER_GUESTBOOK_READ_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x018b)
#define USER_GUESTBOOK_READ_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x018b)

#define USER_PROFILE_BLOCK_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x018c)
#define USER_PROFILE_BLOCK_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x018c)
	#define USER_PROFILE_BLOCK_FAIL_FRIEND		(uint8)(0x01)
	#define USER_PROFILE_BLOCK_FAIL_LIMIT		(uint8)(0x02)
#define USER_PROFILE_BLOCK_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x018c)

#define USER_PROFILE_BLOCK_LIST_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x018d)
#define USER_PROFILE_BLOCK_LIST_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x018d)

#define USER_PROFILE_REPORT_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x018e)
#define USER_PROFILE_REPORT_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x018e)
	#define USER_REPORT_ERROR_LIMIT_TODAY		(uint8)(0x01)
	#define USER_REPORT_ERROR_SAME_USER			(uint8)(0x02)

//////////////////////////////////////////////////////////////////////////////////////////
// post msg
#define POSTMSG_LIST_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0190)
#define POSTMSG_LIST_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0190)
#define POSTMSG_LIST_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0190)

#define POSTMSG_OPENED_LIST_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0191)
#define POSTMSG_OPENED_LIST_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0191)
#define POSTMSG_OPENED_LIST_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0191)

#define POSTMSG_NEW_UNREAD_MSG_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0192)

#define POSTMSG_NEW_READ_MSG_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0193)

#define POSTMSG_RUNTIME_EXPIRED_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0194)

#define POSTMSG_ACTION_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0195)
#define POSTMSG_ACTION_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0195)
	#define POSTMSG_ACTION_FAIL_COMMON			(uint8)0x01
	#define POSTMSG_ACTION_FAIL_OPENED			(uint8)0x02

//////////////////////////////////////////////////////////////////////////////////////////
// npc object
#define NPC_INTERACTION_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0200)
#define NPC_INTERACTION_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0200)
RESULT_CODE_BEGIN(NPC_INTERACTION_FAIL)
	#define NPC_INTERACTION_FAIL_PC_STATE			(uint8)0x01
	#define NPC_INTERACTION_FAIL_NPC_STATE			(uint8)0x02
	#define NPC_INTERACTION_FAIL_NPC				(uint8)0x03
	#define NPC_INTERACTION_FAIL_TOO_FAR			(uint8)0x04
	#define NPC_INTERACTION_FAIL_REFERENCE			(uint8)0x05
	#define NPC_INTERACTION_FAIL_QUEST_COMPLETE		(uint8)0x06
RESULT_CODE_END()

#define NPC_PROFILE_UPDATE_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0201)
#define NPC_PROFILE_UPDATE_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0201)

#define MONSTER_INTERACTION_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0202)
#define MONSTER_INTERACTION_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0202)

#define NPC_BODY_EQUIP_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0203)
#define NPC_BODY_EQUIP_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0203)
#define NPC_BODY_EQUIP_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0203)

//////////////////////////////////////////////////////////////////////////////////////////
// handover
#define HANDOVER_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0219)
#define HANDOVER_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0219)
	#define HANDOVER_FAILED						(uint8)0x01
	#define HANDOVER_DEFAULT_WORLD						(uint8)0x02

#define HANDOVER_STARTED					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0219)

//////////////////////////////////////////////////////////////////////////////////////////
//debug
#define DEBUG_LOCATION_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0220)
#define DEBUG_LOCATION_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0220)

#define DEBUG_VOXEL_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0221)
#define DEBUG_VOXEL_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0221)

IGNORE_STRING_GENERATOR()
#define DEBUG_WORLD_VISUALIZER_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0223)

#define DEBUG_USER_LOG_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0224)
#define DEBUG_USER_LOG_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0224)

//////////////////////////////////////////////////////////////////////////////////////////
//proxy
#define PROXY_ADD_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0230)
#define PROXY_DEL_NFY						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0231)
#define PROXY_UPDATE_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0232)
#define PROXY_UPDATE_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0232)
#define PROXY_UPDATE_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0232)
#define PROXY_COMPLETE_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0233)
#define PROXY_COMPLETE_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0233)

	#define PROXY_CHECKPOINT_INVALID_STEP		(uint8)0x01
	#define PROXY_CHECKPOINT_QUEST_ADDED		(uint8)0x02
	#define PROXY_BALLOON_COUNT_UPDATED			(uint8)0x01
	#define PROXY_BALLOON_SCORE_UPDATED			(uint8)0x02

	#define STAGE_REPORT_ADVENTURE				(uint8)0x01
	#define STAGE_REPORT_SKILL_USED				(uint8)0x02
	#define STAGE_REPORT_DASH_USED				(uint8)0x03
	#define STAGE_REPORT_MONSTER_DEAD			(uint8)0x04
	#define STAGE_REPORT_PC_DEAD				(uint8)0x05

//////////////////////////////////////////////////////////////////////////////////////////
// crew (refactoring)
#define CREW_CMD_LIST_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0240)
#define CREW_CMD_LIST_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0240)

#define CREW_CMD_CREATE_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0241)
#define CREW_CMD_CREATE_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0241)

#define CREW_CMD_SIGN_UP_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0242)
#define CREW_CMD_SIGN_UP_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0242)

#define CREW_CMD_SIGN_OUT_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0243)
#define CREW_CMD_SIGN_OUT_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0243)

#define CREW_CMD_SEARCH_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0244)
#define CREW_CMD_SEARCH_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0244)

#define CREW_CMD_INVITE_CANCEL_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0245)
#define CREW_CMD_INVITE_CANCEL_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0245)

#define CREW_CMD_APPLY_CANCEL_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0246)
#define CREW_CMD_APPLY_CANCEL_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0246)

// crew master cmd
#define CREW_MASTER_CMD_NOTICE_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0247)
#define CREW_MASTER_CMD_NOTICE_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0247)

#define CREW_MASTER_CMD_DESC_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0248)
#define CREW_MASTER_CMD_DESC_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0248)

#define CREW_MASTER_CMD_APPROVAL_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0249)
#define CREW_MASTER_CMD_APPROVAL_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0249)

#define CREW_MASTER_CMD_IMAGE_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x024a)
#define CREW_MASTER_CMD_IMAGE_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x024a)

// crew master manager cmd
#define CREW_MASTER_MANAGE_CMD_EXPEL_REQ	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x024b)
#define CREW_MASTER_MANAGE_CMD_EXPEL_ACK	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x024b)

#define CREW_MASTER_MANAGE_CMD_APPLY_REQ	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x024c)
#define CREW_MASTER_MANAGE_CMD_APPLY_ACK	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x024c)

#define CREW_MASTER_MANAGE_CMD_APPLY_CANCEL_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x024d)
#define CREW_MASTER_MANAGE_CMD_APPLY_CANCEL_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x024d)

#define CREW_MASTER_MANAGE_CMD_INVITE_REQ	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x024e)
#define CREW_MASTER_MANAGE_CMD_INVITE_ACK	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x024e)

#define CREW_MASTER_MANAGE_CMD_INVITE_CANCEL_REQ	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x024f)
#define CREW_MASTER_MANAGE_CMD_INVITE_CANCEL_ACK	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x024f)

// crew member cmd
#define CREW_MEMBER_CMD_INFO_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x250)
#define CREW_MEMBER_CMD_INFO_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x250)

#define CREW_MEMBER_CMD_WARP_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x251)
#define CREW_MEMBER_CMD_WARP_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x251)

// crew display data
#define CREW_DISPLAY_DATA_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x252)
#define CREW_DISPLAY_DATA_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x252)

#define CREW_SEND_TO_MASTER_CANCEL_JOIN_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0253)
#define CREW_SEND_TO_USER_INVITE_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0254)
#define CREW_SEND_TO_USER_CANCEL_INVITE_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0255)

//////////////////////////////////////////////////////////////////////////////////////////
// ranking
#define RANKING_MINE_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0280)
#define RANKING_MINE_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0280)

#define RANKING_LIST_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0281)
#define RANKING_LIST_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0281)

#define RANKING_PERSISTENT_MINE_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0282)
#define RANKING_PERSISTENT_MINE_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0282)

#define RANKING_PERSISTENT_LIST_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0283)
#define RANKING_PERSISTENT_LIST_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0283)

#define RANKING_PERSISTENT_TOP_RANKER_NFY	MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0284)

#define RANKING_QUALIFIER_SCORE_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0285)
#define RANKING_QUALIFIER_SCORE_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0285)

#define RANKING_SCORE_UPDATED_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0286)

//////////////////////////////////////////////////////////////////////////////////////////
//	gm command
#define GM_COMMAND_REQ						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0300)
#define GM_COMMAND_ACK						MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0300)
	#define GM_COMMAND_SUCCESS					(uint8)0x01
	#define GM_COMMAND_FAIL_NO_TARGET			(uint8)0x02
	#define GM_COMMAND_FAIL_UNSPECIFIED			(uint8)0x03

#define GM_COMMAND							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0300)
	#define GM_COMMAND_TRACE_USER_GRID			(uint8)0x01
	#define GM_COMMAND_TRACE_USER_LOG			(uint8)0x02
	#define GM_COMMAND_SET_WORLD_CONNECTION		(uint8)0x03
	#define GM_COMMAND_UNLOCKED_STAGE			(uint8)0x04

#define GAME_MANAGEMENT_SERVICE_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0301)
	#define GAME_MANAGEMENT_SERVICE_UNLOCK_STAGE		(uint8)0x01

//////////////////////////////////////////////////////////////////////////////////////////
// spectating system
#define SPECTATING_STOP_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0311)
#define SPECTATING_STOP_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0311)
	#define SPECTATING_STOP_REASON_USER_REQ			(uint8)0x00
	#define SPECTATING_STOP_REASON_STAGE_FINISHED	(uint8)0x01

#define SPECTATING_READY_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0314)
#define SPECTATING_READY_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0314)

#define SPECTATING_STAGE_FINISHED_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0315)
	#define SPECTATING_FINISHED_TYPE_CLEARED		(uint8)0x00
	#define SPECTATING_FINISHED_TYPE_FAILED			(uint8)0x01

#define SPECTATING_DONATION_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0316)
#define SPECTATING_DONATION_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0316)
#define SPECTATING_DONATION_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0316)
#	define SPECTATING_DONATION_NFY_TYPE_EOF			(uint8)0x00
#	define SPECTATING_DONATION_NFY_TYPE_UPDATED		(uint8)0x01
#	define SPECTATING_DONATION_NFY_TYPE_LOG			(uint8)0x02
#	define SPECTATING_DONATION_NFY_TYPE_RECEIVED	(uint8)0x03
#	define SPECTATING_DONATION_NFY_TYPE_REWARDS		(uint8)0x04

#define SPECTATING_ENQUEUE_AS_TYPE_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0317)
#define SPECTATING_ENQUEUE_AS_TYPE_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0317)

#define SPECTATING_STAGE_INFO_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0318)
#define SPECTATING_STAGE_INFO_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0318)
#define SPECTATING_STAGE_INFO_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0318)

#define SPECTATING_ENQUEUE_RESIGN_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0319)
#define SPECTATING_ENQUEUE_RESIGN_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0319)
#	define SPECTATING_ENQUEUE_TYPE_AS_PLAYER		(uint8)0
#	define SPECTATING_ENQUEUE_TYPE_AS_SPECTATOR		(uint8)1

#define CHAMPIONSHIP_RANKING_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x031C)
#define CHAMPIONSHIP_RANKING_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x031C)

//////////////////////////////////////////////////////////////////////////////////////////
// skilltree
#define SKILLTREE_UPGRADE_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0320)
#define SKILLTREE_UPGRADE_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0320)
	#define SKILLTREE_UPGRADE_FAIL_LOCKED	(uint8)(ERROR_COMMON_MAX + 0x01)
	#define SKILLTREE_UPGRADE_FAIL_MAX		(uint8)(ERROR_COMMON_MAX + 0x02)
	#define SKILLTREE_UPGRADE_FAIL_LICENSE	(uint8)(ERROR_COMMON_MAX + 0x03)
	#define SKILLTREE_UPGRADE_FAIL_COST		(uint8)(ERROR_COMMON_MAX + 0x04)

#define SKILLTREE_EQUIP_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0321)
#define SKILLTREE_EQUIP_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0321)
	#define SKILLTREE_EQUIP_FAIL_LOCKED		(uint8)(ERROR_COMMON_MAX + 0x01)

#define SKILLTREE_RESET_REQ					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0322)
#define SKILLTREE_RESET_ACK					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0322)
	#define SKILLTREE_RESET_FAIL_COST		(uint8)(ERROR_COMMON_MAX + 0x01)

//
// result codes
RESULT_CODE_BEGIN(RESULT_SPECTATING)
#	define RESULT_SPECTATING_SUCCEEDED				(uint8)0x00
#	define RESULT_SPECTATING_HAS_WARNINGS			(uint8)0x01
#   define RESULT_SPECTATING_ENTER_SPECTATOR_WARN	(uint8)0x02

#	define RESULT_SPECTATING_UNEXPECTED_ERROR		(uint8)0x80
#	define RESULT_SPECTATING_STAGE_NOT_VALID		(uint8)0x81
#	define RESULT_SPECTATING_STAGE_NOT_SUPPORT		(uint8)0x82
#	define RESULT_SPECTATING_MIGRATION_FAILED		(uint8)0x83
#	define RESULT_SPECTATING_ENTRY_NOT_VALID		(uint8)0x84
#	define RESULT_SPECTATING_ENTER_FAILED			(uint8)0x85
#	define RESULT_SPECTATING_USER_ALREADY_EXIST		(uint8)0x86
#	define RESULT_SPECTATING_DENIED_BY_RULE			(uint8)0x87
#	define RESULT_SPECTATING_USER_NOT_VALID			(uint8)0x88
#	define RESULT_SPECTATING_FAILED_REQUIREMENTS	(uint8)0x89
#   define RESULT_SPECTATING_FAILED_READY_STAGE		(uint8)0x8A
#   define RESULT_SPECTATING_FAILED_ENQUEUE_USER    (uint8)0x8B
#   define RESULT_SPECTATING_NO_PLAYERS				(uint8)0x8C
#	define RESULT_SPECTATING_PERMISSION_DENIED		(uint8)0x8D
#   define RESULT_SPECTATING_QUEUE_NOT_VALID		(uint8)0x8E
#	define RESULT_SPECTATING_REQUEST_CORRUPTED		(uint8)0x8F
#	define RESULT_SPECTATING_INVALID_TARGET			(uint8)0x90
#	define RESULT_SPECTATING_NOT_ENOUGH_CURRENCY	(uint8)0x91
#	define RESULT_SPECTATING_STAGE_CLOSED			(uint8)0x92
#	define RESULT_SPECTATING_UNDERQUALIFIED			(uint8)0x93
#	define RESULT_SPECTATING_DONATION_COOLDOWN		(uint8)0x94
#	define RESULT_SPECTATING_NOT_AVAILABLE_SCHEDULE (uint8)0x95
RESULT_CODE_END()

#	define SUCCEEDED_RESULT_SPECTATING(x)			((x) <  (uint8)0x80)
#	define FAILED_RESULT_SPECTATING(x)				((x) >= (uint8)0x80)


//////////////////////////////////////////////////////////////////////////////////////////
#define SHAREDQUEST_REQUEST_HELP_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0331)
#define SHAREDQUEST_REQUEST_HELP_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0331)

#define SHAREDQUEST_CONNECTED_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0333)
#define SHAREDQUEST_DISCONNECTED_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0334)

#define SHAREDQUEST_MEMBER_UPDATED_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0335)

#define		SHAREDQUEST_MEMBER_UPDATED_HAS_FLAGS(Flags, Group, Check) \
	/* (Flags & (SHAREDQUEST_MEMBER_UPDATED_MODIFY_FLAGS)) == SHAREDQUEST_MEMBER_UPDATED_MODIFY_INIT */ \
	((Flags & (SHAREDQUEST_MEMBER_UPDATED_ ## Group ## _FLAGS)) == SHAREDQUEST_MEMBER_UPDATED_ ## Group ## _ ## Check)

// SHAREDQUEST_MEMBER_UPDATED_MODIFY_FLAGS(0~3)
#define		SHAREDQUEST_MEMBER_UPDATED_MODIFY_FLAGS		(uint8)0b000000'11
#define		SHAREDQUEST_MEMBER_UPDATED_MODIFY_INIT		(uint8)0b000000'00   // 0
#define		SHAREDQUEST_MEMBER_UPDATED_MODIFY_ADD		(uint8)0b000000'01   // 1
#define		SHAREDQUEST_MEMBER_UPDATED_MODIFY_REMOVE	(uint8)0b000000'10   // 2

// SHAREDQUEST_MEMBER_UPDATED_HOST_FLAGS(0~1)
#define		SHAREDQUEST_MEMBER_UPDATED_HOST_FLAGS		(uint8)0b00000'1'00
#define		SHAREDQUEST_MEMBER_UPDATED_HOST_NO			(uint8)0b00000'0'00  // 0
#define		SHAREDQUEST_MEMBER_UPDATED_HOST_HAS			(uint8)0b00000'1'00  // 1

#define SHAREDQUEST_GOT_REWARDS_NFY					MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0337)

#define SHAREDQUEST_QUERY_MASSIVE_ARBEIT_REQ		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0338)
#define SHAREDQUEST_QUERY_MASSIVE_ARBEIT_ACK		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0338)
#define SHAREDQUEST_QUERY_MASSIVE_ARBEIT_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0338)

#define SHAREDQUEST_MASSIVE_JOIN_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0339)
#define SHAREDQUEST_MASSIVE_JOIN_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0339)
#define SHAREDQUEST_MASSIVE_LEAVE_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x033A)
#define SHAREDQUEST_MASSIVE_LEAVE_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x033A)

#define SHAREDQUEST_SUPPORT_CONTRIBUTION_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x033B)

#define SHAREDQUEST_QUERY_USERDATA_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x033C)
#define SHAREDQUEST_QUERY_USERDATA_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x033C)
#define SHAREDQUEST_QUERY_USERDATA_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x033C)

#define SHAREDQUEST_MASSIVE_STAGE_START_NFY			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x033D)
#define SHAREDQUEST_MASSIVE_ARBEIT_CATEGORY_NFY		MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x033E)


#define CALLRPC_REQ									MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x033E)
#define CALLRPC_ACK									MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x033E)

// result codes
RESULT_CODE_BEGIN(RESULT_SHAREDQUEST)
#	define RESULT_SHAREDQUEST_UNEXPECTED_ERROR		(uint8)0x80
#	define RESULT_SHAREDQUEST_QUERY_USER_INVALID	(uint8)0x81
#	define RESULT_SHAREDQUEST_QUEST_NOT_VALID		(uint8)0x82
#	define RESULT_SHAREDQUEST_NEARLY_COMPLETED		(uint8)0x83
#	define RESULT_SHAREDQUEST_QUEST_NOT_OPENED		(uint8)0x84
#	define RESULT_SHAREDQUEST_MEMBER_NOT_RESERVED	(uint8)0x85
#	define RESULT_SHAREDQUEST_MEMBER_FULL			(uint8)0x86
#	define RESULT_SHAREDQUEST_ACCEPT_TIMED_OUT		(uint8)0x87
#	define RESULT_SHAREDQUEST_ARBEIT_PROGRESS		(uint8)0x88
#	define RESULT_SHAREDQUEST_ALREADY_RESERVED		(uint8)0x89
#	define RESULT_SHAREDQUEST_ALREADY_OPENED		(uint8)0x8A
RESULT_CODE_END()


//////////////////////////////////////////////////////////////////////////////////////////
// global notice messages.
#define GLOBALNOTICE_INIT_NOTICES_REQ				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0340)
#define GLOBALNOTICE_INIT_NOTICES_ACK				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0340)

#define GLOBALNOTICE_GET_NOTICE_INFO_REQ			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0341)
#define GLOBALNOTICE_GET_NOTICE_INFO_ACK			MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0341)

#define GLOBALNOTICE_UPDATE_NOTICES_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0341)

//
// result codes
RESULT_CODE_BEGIN(RESULT_GLOBALNOTICE)
#	define RESULT_GLOBALNOTICE_SUCCEEDED			(uint8)0x00
#	define RESULT_GLOBALNOTICE_INCLUDE_NO_DATA		(uint8)0x01

#	define RESULT_GLOBALNOTICE_UNEXPECTED_ERROR		(uint8)0x80
#	define RESULT_GLOBALNOTICE_NO_DATA				(uint8)0x81
RESULT_CODE_END()

#	define SUCCEEDED_RESULT_GLOBALNOTICE(x)			((x) <  (uint8)0x80)
#	define FAILED_RESULT_GLOBALNOTICE(x)			((x) >= (uint8)0x80)
#	define HAS_WARNING_RESULT_GLOBALNOTICE(x)		((uint8)0 < (x) && (x) < (uint8)0x80)


//////////////////////////////////////////////////////////////////////////////////////////
// coupon messages.
#define COUPON_EXCHANGE_REQ							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0350)
#define COUPON_EXCHANGE_ACK							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0350)

//////////////////////////////////////////////////////////////////////////////////////////
// userdata messages.

#define USER_SAVE_REQ							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0351)
	#define USER_SAVE_PUT						(uint8)0x01
	#define USER_SAVE_SYNCHRONIZE				(uint8)0x02
#define USER_SAVE_ACK							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0351)
#define USER_SAVE_NFY							MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0351)

#define OTHERUSER_SCREENSHOT_REQ                    MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0353)
#define OTHERUSER_SCREENSHOT_ACK                    MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0353)


//////////////////////////////////////////////////////////////////////////////////////////
// tag component.
#define TAG_COMPONENT_SYNCHRONIZE_NFY				MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0360)

//////////////////////////////////////////////////////////////////////////
// char event queue
#define CHAR_EVENT_MESSAGE_RECVED_REQ                MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0361)
#define CHAR_EVENT_MESSAGE_RECVED_ACK                MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0361)
#define CHAR_EVENT_MESSAGE_RECVED_NFY                MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0361)
	#define EVENT_OTHERUSER_SCREENSHOT                (int16)1
	#define EVENT_FASHION_SNAP                        (int16)2

#define ONEOFFPASS_LEVELUP_NFY						 MAKE_CONTENTMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0362)
