#pragma once

#define MSG_FLAG_IDFIELD_NO_DIR             (uint16)0x0000
#define MSG_FLAG_IDFIELD_REQMSG             (uint16)0x4000
#define MSG_FLAG_IDFIELD_ACKMSG             (uint16)0x8000

#define IS_REQMSG(msgid)                    (((msgid) & MSG_FLAG_IDFIELD_REQMSG) == MSG_FLAG_IDFIELD_REQMSG)
#define IS_ACKMSG(msgid)                    (((msgid) & MSG_FLAG_IDFIELD_ACKMSG) == MSG_FLAG_IDFIELD_ACKMSG)

#define	MSG_FLAG_IDFIELD_FRAMEWORK          (uint16)0x2000
#define MAKE_FRAMEWORKMSG(dir, id)          (MSG_FLAG_IDFIELD_FRAMEWORK | (dir) | id)
#define IS_FRAMEWORK_MSG(id)                ((((id & 0x3000) & MSG_FLAG_IDFIELD_FRAMEWORK)) == (((id & 0x3000)| MSG_FLAG_IDFIELD_FRAMEWORK)) )

//////////////////////////////////////////////////////////////////////////////////////////
//common error codes
#define RESULT_SUCCEEDED				(uint8)0x00
#define QUERYTX_FAILED					(uint8)0x01
#define INTERNAL_ERROR					(uint8)0x10
#define INVALID_STATE					(uint8)0x11
#define NO_ENTRY						(uint8)0x12
#define ENTRY_DUPLICATED				(uint8)0x13
#define	OVER_AMOUNT						(uint8)0x14
#define INVALID_TARGET					(uint8)0x15
#define INVALID_PARAM					(uint8)0x16
#define INVENTORY_FULL					(uint8)0x17
#define NOT_ENOUGH_COUNT				(uint8)0x18
#define MSG_FILTERED					(uint8)0x19
#define AQ_RESULT_FAIL					(uint8)0x1a
#define TIMEOUT							(uint8)0x1b
#define NOT_MODIFIED					(uint8)0x1c
#define COMMON_EXPIRED					(uint8)0x20
#define COMMON_PROFILE_BLOCKED			(uint8)0x21
#define COMMON_MAX						(uint8)0x50

//////////////////////////////////////////////////////////////////////////////////////////
#define FRAMEWORKMSG_SETUP_CORD             MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0001)
#define FRAMEWORKMSG_HEART_BEAT_REQ         MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0002)
#define FRAMEWORKMSG_HEART_BEAT_ACK         MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0002)

#define FRAMEWORKMSG_SIGN_IN_REQ            MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0004)
#define FRAMEWORKMSG_SIGN_IN_ACK            MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0004)
	#define SIGN_IN_SUCCEEDED					(uint8)0
	#define SIGN_IN_ERROR_BACKEND_TIMEOUT		(uint8)0x01
	#define SIGN_IN_ERROR_BACKEND				(uint8)0x02
	#define SIGN_IN_INVALID_ACCOUNT_STATE		(uint8)0x03
	#define SIGN_IN_INVALID_AUTH				(uint8)0x04
	#define SIGN_IN_INVALID_TOAST_RESULT_FAILED	(uint8)0x10
	#define SIGN_IN_INVALID_TOAST_ACCOUNT_STATE	(uint8)0x11
	#define SIGN_IN_INVALID_TOAST_UNKNOWN_IDP	(uint8)0x12

#define FRAMEWORKMSG_DISCONTINUE_SESSION    MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0005)

#define FRAMEWORKMSG_WORLD_LIST_REQ         MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0006)
#define FRAMEWORKMSG_WORLD_LIST_ACK         MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0006)

#define FRAMEWORKMSG_QUEUE_UP_IMMIGRATION_WORLD_REQ		MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0007)
#define FRAMEWORKMSG_QUEUE_UP_IMMIGRATION_WORLD_ACK		MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0007)
	#define QUEUE_UP_RESULT_OK					(uint8)0
	#define QUEUE_UP_INTERNAL_DUPLICATION_USER	(uint8)1
	#define	QUEUE_UP_INTERNAL_SERVER_FAILED		(uint8)2
	#define QUEUE_UP_INTERNAL_SERVER_MAINTENANCE (uint8)3
	#define	QUEUE_UP_MAX_CAPACITY				(uint8)4

#define FRAMEWORKMSG_IMMIGRATION_WORLD		MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0008)

#define FRAMEWORKMSG_IMMIGRATION_COMPLETED	MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0009)

#define FRAMEWORKMSG_CONNECT_CERTIFICATION_SERVICE_REQ	MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x000A)
#define FRAMEWORKMSG_CONNECT_CERTIFICATION_SERVICE_ACK	MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x000A)

#define FRAMEWORKMSG_RPC_INVOKE_REQ			MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x000B)
#define FRAMEWORKMSG_RPC_INVOKE_ACK			MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x000B)

#define FRAMEWORKMSG_SYNC_ADDITIONALDATA_NFY	MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x000C)

#define FRAMEWORKMSG_START_ENTER_WORLD_REQ  MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0010)
#define FRAMEWORKMSG_START_ENTER_WORLD_ACK  MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0010)
	#define ENTER_WORLD_RESULT_OK				(uint8)0
	#define ENTER_WORLD_INTERNAL_ERROR			(uint8)2

#define FRAMEWORKMSG_SECURITY_EXCHANGE_REQ  MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0011)
#define FRAMEWORKMSG_SECURITY_EXCHANGE_ACK  MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0011)

#define FRAMEWORKMSG_SECURITY_ERROR			MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0012)

#define FRAMEWORKMSG_ASYNC_QUERY_REQ        MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0020)
#define FRAMEWORKMSG_ASYNC_QUERY_ACK        MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0020)

#define FRAMEWORKMSG_QUERY_CONTENT_INFO_REQ		MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0030)
#define FRAMEWORKMSG_QUERY_CONTENT_INFO_ACK		MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0030)

#define FRAMEWORKMSG_QUERY_ACCOUNT_INFO_REQ		MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0031)
#define FRAMEWORKMSG_QUERY_ACCOUNT_INFO_ACK		MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0031)


#define FRAMEWORKMSG_RELAY_CLIENT_SINGLE    MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0101)
#define FRAMEWORKMSG_RELAY_CLIENT_MULTI     MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0102)

#define FRAMEWORKMSG_TIME_SYNC_REQ          MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0105)
#define FRAMEWORKMSG_TIME_SYNC_ACK          MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0105)

#define FRAMEWORKMSG_DISCONNECTED           MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0106)

#define FRAMEWORKMSG_RENEWAL_SESSION_REQ    MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0107)
#define FRAMEWORKMSG_RENEWAL_SESSION_ACK    MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0107)

#define FRAMEWORKMSG_REPAIR_SESSION_REQ     MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0108)
#define FRAMEWORKMSG_REPAIR_SESSION_ACK     MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0108)
	#define REPAIR_SESSION_INVALID_TOKEN			(uint8)1
	#define REPAIR_SESSION_INTERNAL_SERVER_FAILED	(uint8)2
	#define REPAIR_SESSION_WORLD_SERVER_FAILED		(uint8)3
	#define REPAIR_SESSION_INVALID_STATE			(uint8)4

#define FRAMEWORKMSG_HANDOVER_REQ		    MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0109)
#define FRAMEWORKMSG_HANDOVER_ACK		    MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0109)
	#define HANDOVER_INVALID_STATE					(uint8)1
	#define HANDOVER_INTERNAL_SERVER_FAILED			(uint8)2

#define FRAMEWORKMSG_ENTER_GROUP			MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0110)
#define FRAMEWORKMSG_LEAVE_GROUP			MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0111)
#define FRAMEWORKMSG_MIGRATE_GROUP			MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0112)
#define FRAMEWORKMSG_BROADCAST_GROUP		MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0113)
#define FRAMEWORKMSG_REMOVE_GROUP			MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0114)

#define FRAMEWORKMSG_READY_TO_LOGOUT        MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0120)
#define FRAMEWORKMSG_CONTENT_SERVICE_SHUTDOWN       MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_NO_DIR, 0x0121)


#define FRAMEWORKMSG_DUMMY_SIGN_IN_REQ      MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0200)
#define FRAMEWORKMSG_DUMMY_SIGN_IN_ACK      MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0200)

#define FRAMEWORKMSG_DUMMY_ENTER_WORLD_REQ      MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_REQMSG, 0x0201)
#define FRAMEWORKMSG_DUMMY_ENTER_WORLD_ACK      MAKE_FRAMEWORKMSG(MSG_FLAG_IDFIELD_ACKMSG, 0x0201)

